"""Render the real interface against real engine output, without the shell.

    python -m tools.render_ui --out build/ui
    python -m tools.render_ui --out build/ui --screenshot

**Nothing else in this repository exercises the interface's rendering path.**
`tests/test_desktop_shell.py` checks that `index.html` parses and that it only
calls backend methods which exist. Neither is the same as it drawing the right
thing, and the shell cannot be compiled in this environment to find out.

This builds a standalone page: the real `desktop/dist/index.html`, with
`window.__TAURI__` replaced by a stub that replays **real replies from the real
API** -- no fixtures, no hand-written JSON. Open it in any browser and the
application's screens render exactly as they would in the shell, minus the shell.

It found the launch bug's other half: with the stub returning the buffered
opening line through `drain_backend`, the status bar reads *Offline* instead of
sitting at *starting...* forever.

**The stub is the boundary and it is thin on purpose.** It answers
`call_backend` from a table of captured replies and `drain_backend` from the
captured ready frame. If it grew logic, this would stop being a render of the
application and start being a render of the stub.
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "desktop" / "dist" / "index.html"

#: Every method the interface calls on the plan tab, with the arguments it uses.
#: Kept in this order because a plan must be run before there is anything to
#: report on.
CALLS = (
    ("demo.build", {"seed": 7}),
    ("scenario.growth", {"demand_growth_pct": 0, "capacity_growth_pct": 0}),
    ("plan.run", {}),
    ("plan.risks", {"limit": 50, "worst_first": False}),
    ("plan.orders", {"limit": 100}),
    ("profile.list", {}),
)


def capture() -> tuple:
    """Run the engines and collect one real reply per method."""
    from planbrain.backend.api import METHODS, session
    from planbrain.backend.__main__ import PROTOCOL_VERSION

    state = session(":memory:")
    replies = {}
    for method, params in CALLS:
        print(f"  {method} ...", flush=True)
        replies[method] = {"ok": True, "result": METHODS[method](state, **params)}
    ready = {"ready": True, "protocol": PROTOCOL_VERSION, "offline": True,
             "methods": sorted(METHODS), "database": ":memory:"}
    state.con.close()
    return ready, replies


STUB = """
<script>
// Stub for window.__TAURI__, generated by tools/render_ui.py. Replays replies
// captured from a real run of the engines: what renders below is what the
// application renders.
(function () {
  const READY = %(ready)s;
  const BY_METHOD = %(replies)s;
  const listeners = {};
  let drained = false;

  function emit(event, payload) {
    (listeners[event] || []).forEach(function (cb) { cb({ payload: payload }); });
  }

  window.__TAURI__ = {
    core: {
      invoke: function (cmd, args) {
        if (cmd === "drain_backend") {
          // The buffered opening line, handed over exactly as the Rust does.
          if (drained) { return Promise.resolve([]); }
          drained = true;
          return Promise.resolve([["backend", JSON.stringify(READY)]]);
        }
        if (cmd === "call_backend") {
          const req = JSON.parse(args.request);
          const canned = BY_METHOD[req.method];
          setTimeout(function () {
            emit("backend", JSON.stringify(
              canned
                ? Object.assign({}, canned, { id: req.id })
                : { id: req.id, ok: false,
                    error: { type: "NotCaptured", message: req.method } }
            ));
          }, 0);
        }
        return Promise.resolve();
      }
    },
    event: {
      listen: function (name, cb) {
        (listeners[name] = listeners[name] || []).push(cb);
        return Promise.resolve(function () {});
      }
    },
    // Both dialogs cancel. A render is not a place to write a file, and
    // cancelling is a path the interface has to handle anyway.
    dialog: {
      open: function () { return Promise.resolve(null); },
      save: function () { return Promise.resolve(null); }
    }
  };
})();
</script>
"""

DRIVE = """
<script type="module">
  // Click the flow through, so what is on screen is the populated state.
  const wait = (ms) => new Promise((r) => setTimeout(r, ms));
  await wait(150);
  document.getElementById("loadDemo").click();
  await wait(300);
  document.getElementById("runPlan").click();
  await wait(800);
  document.title = "Planning Brain (rendered)";
</script>
"""


def build(out: Path) -> Path:
    ready, replies = capture()
    index = INDEX.read_text(encoding="utf-8")

    marker = '<script type="module">'
    if index.count(marker) != 1:
        raise SystemExit(
            f"expected exactly one module script in {INDEX}, found "
            f"{index.count(marker)}; the stub has to go before it"
        )
    stub = STUB % {"ready": json.dumps(ready),
                   "replies": json.dumps(replies, default=str)}

    out.mkdir(parents=True, exist_ok=True)
    page = out / "index.html"
    page.write_text(index.replace(marker, stub + marker) + DRIVE, encoding="utf-8")
    return page


#: Where a headless browser lives on each platform. Only used by --screenshot,
#: which is optional: the page is the deliverable and any browser will open it.
BROWSERS = (
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/usr/bin/google-chrome",
    "/usr/bin/chromium",
)


def screenshot(page: Path, shot: Path, *, height: int = 1700) -> bool:
    browser = next((b for b in BROWSERS if Path(b).exists()), None)
    if browser is None:
        print("no headless browser found; open the page by hand", file=sys.stderr)
        return False
    subprocess.run(
        [browser, "--headless=new", "--disable-gpu", "--hide-scrollbars",
         f"--window-size=1280,{height}", f"--screenshot={shot}",
         "--virtual-time-budget=8000", page.as_uri()],
        check=False, capture_output=True,
    )
    return shot.exists()


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="build/ui")
    parser.add_argument("--screenshot", action="store_true")
    parser.add_argument("--height", type=int, default=1700)
    args = parser.parse_args(argv)

    page = build(Path(args.out).resolve())
    print(f"rendered {page}")
    if args.screenshot:
        shot = page.with_name("ui.png")
        if screenshot(page, shot, height=args.height):
            print(f"screenshot {shot} ({shot.stat().st_size:,} bytes)")
        else:
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
