"""Render the real interface against real engine output, without the shell.

    python -m tools.render_ui --out build/ui
    python -m tools.render_ui --out build/ui --screenshot

**Nothing else in this repository exercises the interface's rendering path.**
`tests/test_desktop_shell.py` checks that `index.html` parses and that it only
calls backend methods which exist. Neither is the same as it drawing the right
thing, and the shell cannot be compiled in this environment to find out.

This builds a standalone page: the real `desktop/dist/index.html`, with
`window.__TAURI__` replaced by a stub that replays **real replies from the real
API** -- no fixtures, no hand-written JSON. Open it in any browser and the
application's screens render exactly as they would in the shell, minus the shell.

It found the launch bug's other half: with the stub returning the buffered
opening line through `drain_backend`, the status bar reads *Offline* instead of
sitting at *starting...* forever.

**The stub is the boundary and it is thin on purpose.** It answers
`call_backend` from a table of captured replies and `drain_backend` from the
captured ready frame. If it grew logic, this would stop being a render of the
application and start being a render of the stub.
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "desktop" / "dist" / "index.html"

#: Every method the interface calls on the plan tab, with the arguments it uses.
#: Kept in this order because a plan must be run before there is anything to
#: report on.
CALLS = (
    ("demo.build", {"seed": 7}),
    ("scenario.growth", {"demand_growth_pct": 0, "capacity_growth_pct": 0}),
    ("plan.run", {}),
    ("plan.risks", {"limit": 50, "worst_first": False}),
    ("plan.orders", {"limit": 100}),
    ("override.list", {"limit": 50}),
    ("profile.list", {}),
)


def capture(*, with_override: bool = False) -> tuple:
    """Run the engines and collect one real reply per method.

    ``with_override`` fixes one quantity first, so the *numbers you fixed*
    screen renders populated rather than empty. It is a real override written
    through the real API -- the demo shows the feature working, not a mock-up of
    it working.
    """
    from planbrain.backend.api import METHODS, session
    from planbrain.backend.__main__ import PROTOCOL_VERSION

    state = session(":memory:")
    replies = {}
    if with_override:
        METHODS["demo.build"](state, seed=7)
        METHODS["plan.run"](state)
        sku_id, when, was = _a_planned_receipt(state)
        METHODS["override.set"](
            state, sku_id=sku_id, bucket_date=when.isoformat(),
            qty=round(was * 0.6),
            author="priya",
            reason="Kapoor confirmed a smaller batch on the phone",
        )
        print(f"  fixed {sku_id} on {when} at 60% of {was:,.0f}")
    for method, params in CALLS:
        print(f"  {method} ...", flush=True)
        replies[method] = {"ok": True, "result": METHODS[method](state, **params)}
    ready = {"ready": True, "protocol": PROTOCOL_VERSION, "offline": True,
             "methods": sorted(METHODS), "database": ":memory:"}
    state.con.close()
    return ready, replies


def _a_planned_receipt(state):
    """An (sku, date, qty) the plan actually schedules, to override."""
    from planbrain.facts.access import read_facts

    demo = state.demo
    rows = read_facts(
        state.con, "fact_supply_demand", scenario_id=0,
        measure="planned_order_receipt",
        start=demo.horizon_start, end=demo.horizon_end,
        keys=[(p.sku_id, loc.loc_id) for p in demo.parts for loc in demo.locations],
    )
    for fact in rows:
        if fact.qty:
            return fact.keys[0], fact.bucket_date, fact.qty
    raise SystemExit("the demo plan schedules no receipts to override")


STUB = """
<script>
// Stub for window.__TAURI__, generated by tools/render_ui.py. Replays replies
// captured from a real run of the engines: what renders below is what the
// application renders.
(function () {
  const READY = %(ready)s;
  const BY_METHOD = %(replies)s;
  const listeners = {};
  let drained = false;

  function emit(event, payload) {
    (listeners[event] || []).forEach(function (cb) { cb({ payload: payload }); });
  }

  window.__TAURI__ = {
    core: {
      invoke: function (cmd, args) {
        if (cmd === "drain_backend") {
          // The buffered opening line, handed over exactly as the Rust does.
          if (drained) { return Promise.resolve([]); }
          drained = true;
          return Promise.resolve([["backend", JSON.stringify(READY)]]);
        }
        if (cmd === "call_backend") {
          const req = JSON.parse(args.request);
          const canned = BY_METHOD[req.method];
          setTimeout(function () {
            emit("backend", JSON.stringify(
              canned
                ? Object.assign({}, canned, { id: req.id })
                : { id: req.id, ok: false,
                    error: { type: "NotCaptured", message: req.method } }
            ));
          }, 0);
        }
        return Promise.resolve();
      }
    },
    event: {
      listen: function (name, cb) {
        (listeners[name] = listeners[name] || []).push(cb);
        return Promise.resolve(function () {});
      }
    },
    // Both dialogs cancel. A render is not a place to write a file, and
    // cancelling is a path the interface has to handle anyway.
    dialog: {
      open: function () { return Promise.resolve(null); },
      save: function () { return Promise.resolve(null); }
    }
  };
})();
</script>
"""

DRIVE = """
<script type="module">
  // Click the flow through, so what is on screen is the populated state.
  const wait = (ms) => new Promise((r) => setTimeout(r, ms));
  await wait(150);
  document.getElementById("loadDemo").click();
  await wait(300);
  document.getElementById("runPlan").click();
  await wait(900);
  if (%(import_tab)s) { document.getElementById("tabImport").click(); }
  document.title = "Planning Brain (rendered)";
</script>
"""


def build(out: Path, *, with_override: bool = False,
          import_tab: bool = False, name: str = "index.html") -> Path:
    # Refuse to stub the bridge unless the real application would have one.
    #
    # This harness defines `window.__TAURI__` in order to replay replies, and
    # for one release that hid the fact that the shipped application had no
    # such global at all: `withGlobalTauri` was absent, the frontend threw on
    # its first line, and every button in the window was dead while this
    # rendered perfectly. A stub that supplies the thing whose absence is the
    # bug cannot find that bug, so it refuses to try.
    conf = json.loads(
        (ROOT / "desktop" / "src-tauri" / "tauri.conf.json").read_text(encoding="utf-8")
    )
    if not conf.get("app", {}).get("withGlobalTauri", False):
        raise SystemExit(
            "tauri.conf.json does not set app.withGlobalTauri, so the real "
            "application has no window.__TAURI__ and its frontend cannot run. "
            "Rendering it here with a stubbed global would be a picture of "
            "something that does not work."
        )

    ready, replies = capture(with_override=with_override)
    index = INDEX.read_text(encoding="utf-8")

    marker = '<script type="module">'
    if index.count(marker) != 1:
        raise SystemExit(
            f"expected exactly one module script in {INDEX}, found "
            f"{index.count(marker)}; the stub has to go before it"
        )
    stub = STUB % {"ready": json.dumps(ready),
                   "replies": json.dumps(replies, default=str)}

    out.mkdir(parents=True, exist_ok=True)
    page = out / name
    drive = DRIVE % {"import_tab": "true" if import_tab else "false"}
    page.write_text(index.replace(marker, stub + marker) + drive, encoding="utf-8")
    return page


#: Where a headless browser lives on each platform. Only used by --screenshot,
#: which is optional: the page is the deliverable and any browser will open it.
BROWSERS = (
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/usr/bin/google-chrome",
    "/usr/bin/chromium",
)


def screenshot(page: Path, shot: Path, *, height: int = 1700) -> bool:
    browser = next((b for b in BROWSERS if Path(b).exists()), None)
    if browser is None:
        print("no headless browser found; open the page by hand", file=sys.stderr)
        return False
    subprocess.run(
        [browser, "--headless=new", "--disable-gpu", "--hide-scrollbars",
         f"--window-size=1280,{height}", f"--screenshot={shot}",
         "--virtual-time-budget=8000", page.as_uri()],
        check=False, capture_output=True,
    )
    return shot.exists()


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="build/ui")
    parser.add_argument("--screenshot", action="store_true")
    parser.add_argument("--height", type=int, default=1700)
    parser.add_argument("--with-override", action="store_true",
                        help="fix one quantity first, so the overrides screen "
                             "renders populated")
    parser.add_argument("--import-tab", action="store_true",
                        help="capture the import tab instead of the plan tab")
    parser.add_argument("--name", default="index.html")
    args = parser.parse_args(argv)

    page = build(Path(args.out).resolve(), with_override=args.with_override,
                 import_tab=args.import_tab, name=args.name)
    print(f"rendered {page}")
    if args.screenshot:
        shot = page.with_suffix(".png")
        if screenshot(page, shot, height=args.height):
            print(f"screenshot {shot} ({shot.stat().st_size:,} bytes)")
        else:
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
